#!/bin/sh
# Script para generar vistas previas, de un video.
if ! command -v ffmpeg &> /dev/null || ! command -v montage &> /dev/null; then
    echo "This script requires FFmpeg and ImageMagick"
    exit 1
fi

if [ -z "$1" ] || [ -z "$2" ]; then
    echo "Usage: $0 <video_file> <gallery_title>"
    exit 1
fi

video_file="$1"
gallery_title="$2"
temp_dir=$(mktemp -d)
font_file="$HOME/.local/share/fonts/mononoki/mononoki-Bold.ttf"

ffmpeg -i "$video_file" -r 1/200 -vf "drawtext=fontfile=$font_file:timecode='13\\:19\\:13\\:33':r=30:fontcolor=white:fontsize=92:x=10:y=10:box=1:boxcolor=black@0.5, scale=-2:420" -vcodec png "$temp_dir/capture-%002d.png" || exit 1
montage -title "$gallery_title" -tile x4 -geometry +10+10 "$temp_dir"/*.png "${video_file}.png" || exit 1

rm -rf "$temp_dir"
