#!/bin/sh

msg() {
    printf "%s\n" "$@"
}

fz="fnf --cycle -m"
# colors
RED=$(printf '%b' "\033[1;31m")
GREEN=$(printf '%b' "\033[1;32m")
YELLOW=$(printf '%b' "\033[1;33m")
BLUE=$(printf '%b' "\033[1;34m")
PINK=$(printf '%b' "\033[1;35m")
CYAN=$(printf '%b' "\033[1;36m")
GRAY=$(printf '%b' "\033[0;37m")
WHITE=$(printf '%b' "\033[1;37m")
BOLD=$(printf '%b' "\033[1m")
NORM=$(printf '%b' "\033[0m")


tdir=/media/datos/varios/sfeed/tfeeds
tfile="$XDG_CONFIG_HOME/sfeed/torrentrc"

cd /media/datos/downloads/torrent/watch/start

mtorrent(){
printf "%s\n" "$url" | sed 's/.\{9\}$/.torrent/' > /tmp/tfile
while IFS= read -r line ; do
curl -sLO $line &
done < /tmp/tfile
truncate -s 0 /tmp/tfile
}

update() {
clear
printf "${PINK}Updating feeds ...... ${NORM}"
sfeed_update $tfile > /dev/null  2<&-
clear
}

fetch() {

    while true ; do
    url=$(sfeed_plain $tdir/$1 | grep '^N' | $fz --prompt="$name Feeds: " | sed -n 's@^.* \([a-zA-Z]*://\)\(.*\)$@\1\2@p')
    [ -z "$url" ] && menu
    mtorrent
    done
}

packs() {
name=Packs
fetch P.TorrentGalaxy
}

series() {
name=Series
fetch S.TorrentGalaxy
}

movies() {
name=Movies
fetch M.TorrentGalaxy
}

find() {
name=Find
fetch Seach.TorrentGalaxy
}


clean() {
for i in $(ls $tdir/O*) ; do
awk -F '\t' -v "old=$(($(date +'%s') - 86400))" 'int($1) > old' < $i > ${i}.new
rm $i 
mv ${i}.new $i
clear
done
menu
}
menu() {

    while true ; do
    opt=$(msg Update Episodes Packs Movies Clean Find | $fz -l 6 --prompt="Choose and Option: ")
    [ -z "$opt" ] && exit 0
    case "$opt" in
	Update) update ;;
	Clean) clean ;;
	Episodes) series ;;
	Packs) packs ;;
	Movies) movies ;;
  Find) find ;;
esac
done

}

menu
